Pin i18ndude to 4.4.0 version.
The newer 5.x.x version of i18ndude is no longer compatible with Plone
4.2.

```
While:
  Installing i18ndude.
Error: The requirement ('zope.tal>=4.3.0') is not allowed by your [versions] constraint (3.5.2)
```